name: learn_english
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Quiz & Animation
  flip_card: ^0.7.0
  confetti: ^0.7.0
  lottie: ^3.1.0

  # UI & Fonts
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

  # PDF / Printing
  printing: ^5.12.0
  pdf: ^3.10.0

  # Hive (Local storage)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.2
  firebase_auth_platform_interface: ^7.0.6
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6

  # Auth & Storage
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Network & Security
  http: ^1.1.0
  crypto: ^3.0.3

  # Media & Upload
  image_picker: ^1.0.7
  cloudinary_public: ^0.21.0

  # Config
  flutter_dotenv: ^5.1.0

  # State management
  provider: ^6.1.1

  # Exam / Import feature
  file_picker: ^8.1.3
  syncfusion_flutter_pdf: ^24.0.0
  archive: ^3.4.0
  xml: ^6.3.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/animations/loading_quiz.json
